bizizbizi/apps/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('detail_spot/<pk>/', views.PostDetailView.as_view(), name='detail_spot'),
    path('detail_travel/<pk>/', views.TravelDetailView.as_view(), name='detail_travel'),
    path('api_get/', views.GpsTrackingApiView.as_view(), name='api_get'),
    path('api_post/', views.GpsTrackingView, name='api_post'),
    path('realtime/', views.realtime, name='realtime'),
    path('travels/', views.travels, name="travels"),
    path('', views.index, name="home"),

]

bizizbizi/bizizbizi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from apps.core import views as core_view
from apps.profiles.urls import profiles_patterns

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView
)

urlpatterns = [
    path('', include('apps.core.urls')),
    # Paths de Auth
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('accounts/', include('apps.registration.urls')),
    # Path profile
    path('profiles/', include(profiles_patterns)),
    # admin
    path('admin/', admin.site.urls),
    # api
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('hello/', core_view.HelloView.as_view(), name='hello'),
    # django-allauth
    path('accounts/', include('allauth.urls')),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bizizbizi/apps/core/models.py
from django.db import models
from ckeditor.fields import RichTextField


class Country(models.Model):
    name = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Country"
        verbose_name_plural = "Countries"
        ordering = ["created"]

    def __str__(self):
        return self.name


# Create your models here.
class BikeSpot(models.Model):
    order = models.IntegerField(null=True, blank=True)
    title = models.CharField(max_length=200, null=True, blank=True)
    country = models.ForeignKey(Country, null=True, blank=True, on_delete=models.CASCADE)
    town = models.CharField(max_length=200, null=True, blank=True)
    start_latitude = models.FloatField(null=True, blank=True)
    start_longitude = models.FloatField(null=True, blank=True)
    mid_latitude = models.FloatField(null=True, blank=True)
    mid_longitude = models.FloatField(null=True, blank=True)
    end_latitude = models.FloatField(null=True, blank=True)
    end_longitude = models.FloatField(null=True, blank=True)
    description = RichTextField(null=True, blank=True)
    image1 = models.ImageField(null=True, blank=True, upload_to="img/stage")
    image2 = models.ImageField(null=True, blank=True, upload_to="img/stage")
    image3 = models.ImageField(null=True, blank=True, upload_to="img/stage")
    image4 = models.ImageField(null=True, blank=True, upload_to="img/stage")
    image5 = models.ImageField(null=True, blank=True, upload_to="img/stage")
    image6 = models.ImageField(null=True, blank=True, upload_to="img/stage")
    image7 = models.ImageField(null=True, blank=True, upload_to="img/stage")
    image8 = models.ImageField(null=True, blank=True, upload_to="img/stage")
    gpx = models.BooleanField(null=True, blank=True, verbose_name='gpx')
    auto_gpx = models.BooleanField(null=True, blank=True, verbose_name='auto_gpx')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Stage"
        verbose_name_plural = "Stages"
        ordering = ["order"]

    def __str__(self):
        return self.title


class OpenWeatherMap(models.Model):
    title = models.CharField(max_length=200, null=True, blank=True, verbose_name='Izena')
    owm = models.CharField(max_length=200, null=True, blank=True, verbose_name='code')
    path = models.CharField(max_length=200, null=True, blank=True, verbose_name='webpath')
    euskalmet = models.CharField(max_length=200, null=True, blank=True, verbose_name='euskalmet icon')
    euskalmet_new = models.CharField(max_length=200, null=True, blank=True, verbose_name='euskalmet icon new')
    icon = models.ImageField(null=True, blank=True, verbose_name='Icon', upload_to="projects")
    created = models.DateTimeField(auto_now_add=True, verbose_name='Sortze data')
    updated = models.DateTimeField(auto_now=True, verbose_name='Edizio data')

    class Meta:
        verbose_name = "OpenWeatherMap"
        verbose_name_plural = "OpenWeatherMap"
        ordering = ["created"]

    def __str__(self):
        return self.title


class Warmshower(models.Model):
    title = models.CharField(max_length=200, null=True, blank=True)
    country = models.ForeignKey(Country, null=True, blank=True, on_delete=models.CASCADE)
    town = models.CharField(max_length=200, null=True, blank=True)
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    description = RichTextField(null=True, blank=True)
    image1 = models.ImageField(null=True, blank=True, upload_to="img/warmshower")
    image2 = models.ImageField(null=True, blank=True, upload_to="img/warmshower")
    image3 = models.ImageField(null=True, blank=True, upload_to="img/warmshower")
    image4 = models.ImageField(null=True, blank=True, upload_to="img/warmshower")
    image5 = models.ImageField(null=True, blank=True, upload_to="img/warmshower")
    image6 = models.ImageField(null=True, blank=True, upload_to="img/warmshower")
    image7 = models.ImageField(null=True, blank=True, upload_to="img/warmshower")
    image8 = models.ImageField(null=True, blank=True, upload_to="img/warmshower")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Warmshower"
        verbose_name_plural = "Warmshowers"
        ordering = ["created"]

    def __str__(self):
        return self.title


class GpsTracks(models.Model):
    title = models.CharField(max_length=200, null=True, blank=True)
    country = models.ForeignKey(Country, null=True, blank=True, on_delete=models.CASCADE)
    town = models.CharField(max_length=200, null=True, blank=True)
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    done = models.BooleanField(null=True, blank=True)
    gpx_path = models.FileField(upload_to="gpx_path")
    gpx = models.BooleanField(null=True, blank=True, verbose_name='gpx')
    auto_gpx = models.BooleanField(null=True, blank=True, verbose_name='auto_gpx')
    color = models.CharField(max_length=100, null=True, blank=True)
    description = RichTextField(null=True, blank=True)
    image1 = models.ImageField(null=True, blank=True, upload_to="img/gps_track")
    image2 = models.ImageField(null=True, blank=True, upload_to="img/gps_track")
    image3 = models.ImageField(null=True, blank=True, upload_to="img/gps_track")
    image4 = models.ImageField(null=True, blank=True, upload_to="img/gps_track")
    image5 = models.ImageField(null=True, blank=True, upload_to="img/gps_track")
    image6 = models.ImageField(null=True, blank=True, upload_to="img/gps_track")
    image7 = models.ImageField(null=True, blank=True, upload_to="img/gps_track")
    image8 = models.ImageField(null=True, blank=True, upload_to="img/gps_track")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "GpsTrack"
        verbose_name_plural = "GpsTracks"
        ordering = ["created"]

    def __str__(self):
        return self.title


class Icon(models.Model):
    title = models.CharField(max_length=200, null=True, blank=True)
    start = models.ImageField(null=True, blank=True, upload_to="img/icon")
    start_flag = models.ImageField(null=True, blank=True, upload_to="img/icon")
    end = models.ImageField(null=True, blank=True, upload_to="img/icon")
    end_flag = models.ImageField(null=True, blank=True, upload_to="img/icon")
    shadow = models.ImageField(null=True, blank=True, upload_to="img/icon")
    bike = models.ImageField(null=True, blank=True, upload_to="img/icon")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Icon"
        verbose_name_plural = "Icons"
        ordering = ["created"]

    def __str__(self):
        return self.title


class PointsInterest(models.Model):
    title = models.CharField(max_length=200, null=True, blank=True)
    description = RichTextField(null=True, blank=True)
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    youtube = models.CharField(max_length=500, null=True, blank=True)
    image1 = models.ImageField(null=True, blank=True, upload_to="img/pointsInterest")
    image2 = models.ImageField(null=True, blank=True, upload_to="img/pointsInterest")
    image3 = models.ImageField(null=True, blank=True, upload_to="img/pointsInterest")
    image4 = models.ImageField(null=True, blank=True, upload_to="img/pointsInterest")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Interesting point"
        verbose_name_plural = "Points of interest"
        ordering = ["created"]

    def __str__(self):
        return self.title


class GpsTrackingData(models.Model):
    title = models.CharField(max_length=200, null=True, blank=True)
    date_time = models.DateTimeField(null=True, blank=True, verbose_name="fechahora")
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    track_data = models.JSONField(null=True, blank=True, verbose_name="Tracking data")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "GpsTrackingData"
        verbose_name_plural = "GpsTrackingData"
        ordering = ["created"]

    def __str__(self):
        return self.title

bizizbizi/apps/core/views.py
from django.shortcuts import render

from django.views.generic.detail import DetailView
from .models import BikeSpot, OpenWeatherMap, GpsTracks, GpsTrackingData
from .models import Icon
from rest_framework.generics import ListAPIView, CreateAPIView
from rest_framework.views import APIView
from rest_framework.response import Response
from .serializers import GpsTrackinSerializer
from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework import status
from rest_framework.authentication import SessionAuthentication, BasicAuthentication, TokenAuthentication
from rest_framework.permissions import IsAuthenticated


def index(request):
    bikespot = BikeSpot.objects.all().order_by("order")
    owms = OpenWeatherMap.objects.all()
    icon = Icon.objects.all()
    return render(request, "core/map.html", {'bikespot': bikespot,
                                             'owms': owms,
                                             'icon': icon})


def travels(request):
    biketravel = GpsTracks.objects.all()
    icon = Icon.objects.all()
    return render(request, "core/travel.html", {'biketravel': biketravel,
                                                'icon': icon})


# Create your views here.
class PostDetailView(DetailView):
    model = BikeSpot
    template_name = "core/detail_view.html"

    def get_context_data(self, **kwargs):
        name = self.kwargs['pk']
        context = super().get_context_data(**kwargs)
        context['biketravel'] = BikeSpot.objects.get(id=name)
        print(context)
        return context


class TravelDetailView(DetailView):
    model = GpsTracks
    template_name = "core/detail_view.html"

    def get_context_data(self, **kwargs):
        name = self.kwargs['pk']
        context = super().get_context_data(**kwargs)
        context['biketravel'] = GpsTracks.objects.get(id=name)
        print(context)
        # context['icon'] = Icon.objects.get(id=name)
        print(context)
        return context


# @api_view(['GET'])
@authentication_classes([SessionAuthentication, BasicAuthentication])
@permission_classes([IsAuthenticated])
class GpsTrackingApiView(ListAPIView):
    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAuthenticated]
    serializer_class = GpsTrackinSerializer

    def get_queryset(self):
        return GpsTrackingData.objects.all()


@api_view(['POST'])
@authentication_classes([SessionAuthentication, BasicAuthentication, TokenAuthentication])
@permission_classes([IsAuthenticated])
def GpsTrackingView(request):
    if request.method == 'POST':
        serializer = GpsTrackinSerializer(data=request.data)
        if serializer.is_valid(raise_exception=True):
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


def realtime(request):
    return render(request, "core/realTime.html")


class ExampleView(APIView):
    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAuthenticated]

    def get(self, request, format=None):
        content = {
            'user': str(request.user),  # `django.contrib.auth.User` instance.
            'auth': str(request.auth),  # None
        }
        return Response(content)


class HelloView(APIView):
    permission_classes = (IsAuthenticated,)

    def get(self, request):
        content = {'message': 'Hello, World!'}
        return Response(content)

bizizbizi/templates/core/base.html
<!doctype html>
<html lang="en">

<head>
    <title>BizizBizi</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Eskaladako krosikak ikusteko webgunea">
    <meta name="keywords" content="Eskalada, Euskal Herria, Krokisak, Eguraldia, Eskalada ikastaroak">
    <meta name="author" content="Imanol Areizaga">

    {% load static %}
		<link type="text/css" rel="stylesheet" href="https://unpkg.com/leaflet-routing-machine@3.2.7/dist/leaflet-routing-machine.css" />

    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="navbar.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    <!-- Maps -->
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/leaflet.locatecontrol@0.76.1/dist/L.Control.Locate.min.css"/>

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"
          integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ=="
          crossorigin=""/>
    <link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.3.0/dist/MarkerCluster.css"/>
    <link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.3.0/dist/MarkerCluster.Default.css"/>


    <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://unpkg.com/leaflet@1.8.0/dist/leaflet.js"
            integrity="sha512-BB3hKbKWOc9Ez/TAwyWxNXeoV9c1v6FIeYiBieIWkpLjauysF18NzgR1MBNBXf8/KABdlkX68nAhlwcDFLGPCQ=="
            crossorigin="">
    </script>
    <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
            integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
            crossorigin=""></script>

    <script src="https://cdn.jsdelivr.net/npm/leaflet.locatecontrol@0.76.1/dist/L.Control.Locate.min.js"
            charset="utf-8"></script>
    <script src="https://unpkg.com/leaflet.markercluster@1.3.0/dist/leaflet.markercluster.js"></script>



    <title>{% block title %}{% endblock %} | Mundu bertikala</title>
	<style>
		body {
			margin: 0;
		}
		html, body, #leaflet {
			height: 95%
		}
	</style>
</head>
<header>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'core:home' %}">BizizBizi</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Honi buruz <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:travels' %}">Egindako bidaiak</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Kolaboratu</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://asfape.org/">ASFAPE</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://es.warmshowers.org/">Warmshower</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://en.eurovelo.com/">Eurovelo</a>
      </li>
    </ul>
      <ul class="navbar-nav navbar-right ml-auto">
              {% if not request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" style="font-family:verdana" href="#">Nire gunea</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" style="font-family:verdana" href="#">Izena eman</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" style="font-family:verdana" href="#">Ongi etorri <b style="color:white;">{{ request.user }}</b></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" style="font-family:verdana" href="#">Irten</a>
                </li>
              {% endif %}
            </ul>

  </div>
</nav>
</header>

<body>

{% block content %} {% endblock %}

<!-- Footer -->

<footer>
        <a href="mailto:mundubertikala@gmail.com" style="text-decoration:none;">mundubertikala@gmail.com</a></p>
</footer>

<!--<footer class="footer mt-auto py-3 bg-light">-->
<!--  <div class="container">-->
<!--    <span class="text-muted">Place sticky footer content here.</span>-->
<!--  </div>-->
<!--</footer>-->
<!-- Footer -->
<!--<script type="text/javascript" src="{% static 'core/js/map.js' %}"></script>-->

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
-->
</body>
</html>

bizizbizi/templates/core/travel.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Hasiera{% endblock %}

{% block content %}
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>

<style>
    body {
        padding: 5;
        margin: 0;
    }
    html, body, #map {
        height: 92%;
        width: 100vw;
    }

</style>
<div id="map"></div>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/leaflet.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/leaflet.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-gpx/1.7.0/gpx.min.js"></script>
<script type="text/javascript">
{% for ic in icon %}

        var map = L.map('map').setView([43.261290083983944, -1.9529219919471679], 5);

        var ocm = L.tileLayer('https://tile.thunderforest.com/cycle/{z}/{x}/{y}.png?apikey=cd56115c8eca4973aa4117461a378787', {
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        });

        var osm = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        });

        var OpenTopoMap = L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png', {
            attribution: 'Map data: &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, <a href="http://viewfinderpanoramas.org">SRTM</a> | Map style: &copy; <a href="https://opentopomap.org">OpenTopoMap</a> (<a href="https://creativecommons.org/licenses/by-sa/3.0/">CC-BY-SA</a>)'
        });

        // water color
        var watercolor = L.tileLayer('https://stamen-tiles-{s}.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.{ext}', {
            attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            subdomains: 'abcd',
            minZoom: 1,
            maxZoom: 16,
            ext: 'jpg'
        });

        // dark map
        var dark = L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png', {
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
            subdomains: 'abcd',
            maxZoom: 19
        });
        // google street
        googleStreets = L.tileLayer('http://{s}.google.com/vt/lyrs=m&x={x}&y={y}&z={z}', {
            maxZoom: 20,
            subdomains: ['mt0', 'mt1', 'mt2', 'mt3']
        });

        //google satellite
        googleSat = L.tileLayer('http://{s}.google.com/vt/lyrs=s&x={x}&y={y}&z={z}', {
            maxZoom: 20,
            subdomains: ['mt0', 'mt1', 'mt2', 'mt3']
        });

        var OpenTopoMap = L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
            attribution: 'Map data: &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, <a href="http://viewfinderpanoramas.org">SRTM</a> | Map style: &copy; <a href="https://opentopomap.org">OpenTopoMap</a> (<a href="https://creativecommons.org/licenses/by-sa/3.0/">CC-BY-SA</a>)'
        });


        /*==============================================
                        LAYER CONTROL
        ================================================*/
        var baseMaps = {
            "OpenCycleMap": ocm,
            "OSM": osm,
            'Dark': dark,
            'Google Street': googleStreets,
            "Google Satellite": googleSat,
            "Topo Map": OpenTopoMap,
        };


        var tiles = L.tileLayer('https://tile.thunderforest.com/cycle/{z}/{x}/{y}.png?apikey=cd56115c8eca4973aa4117461a378787').addTo(map);

    {% for spot in biketravel %}
        console.log('{{ spot.gpx_path.url }}');
        var gpx = '{{ spot.gpx_path.url }}'; // URL to your GPX file or the GPX itself
        new L.GPX(gpx, {async: true,
                        marker_options: {
                            startIconUrl: '{{none}}', //'{{ ic.start_flag.url }}',
                            endIconUrl: '{{none}}', //{{ ico.end_flag.url }}',
                            shadowUrl: '{{none}}'
                            },
                        polyline_options: {
                            color: '{{ spot.color }}',
                            opacity: 0.75,
                            weight: 3,
                            lineCap: 'round'
                            },
            }).on('loaded', function(e) {
        }).addTo(map).bindPopup("<a href={% url 'core:detail_travel' spot.id %}>{{ spot.title }}</a><br>");
    {% endfor %}
{% endfor %}

</script>
<!--Jquery -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" crossorigin="anonymous"></script>
<!-- Owl Carousel -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
<!-- custom JS code after importing jquery and owl -->
<script type="text/javascript">
 $(document).ready(function(){
  $('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    autoplay: true,
    center:true,
    items: 1,
    onInitialize: function (event) {
        if ($('.owl-carousel .item').length <= 1) {
           this.settings.loop = false;
        }
    },
    responsive: {
            0: {
                items: 1
            },
            600: {
                items: 2
            },
            1000: {
                items: 3
            }
        },
  })
});

</script>
{% endblock %}